// "use client";
// import { useState, useEffect } from "react";
import "../css/globals.css";

import { ModalProvider } from "../context/QuickViewModalContext";
import { CartModalProvider } from "../context/CartSidebarModalContext";
import { ReduxProvider } from "@/components/ClientComponent/redux/provider";
import { config } from '@fortawesome/fontawesome-svg-core';

// FontAwesome 자동 CSS 추가 방지 설정
config.autoAddCss = false;
import { Geist, Geist_Mono } from "next/font/google";
import Topbar from "@/components/ServerComponent/Topbar";   // Topbar import 추가
import type { Metadata } from "next";

// Google Fonts 설정
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <ModalProvider>
            <CartModalProvider>
               {/* Topbar 추가 */}
               <Topbar />  

              {children}
            </CartModalProvider>
          </ModalProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}


